### ISSUE TITLE
Threshold to start scroll

### ISSUE THREAD

**Issue by MrMaxxan** [iamjosephmj/flinger#30]
Is it possible to set a threshold, that the user needs to move the finger X pixels until it actually starts to scroll?

**Comment by iamjosephmj** [comment]
@MrMaxxan are you referring to "scroll to position" before the user actually touches the screen? Please correct me if I am wrong..

**Comment by iamjosephmj** [comment]
@MrMaxxan I am closing the issue as this is not related to the flinger library.
