### ISSUE TITLE
Sample APK can't be installed

### ISSUE THREAD

**Issue by ptrckSTL** [iamjosephmj/flinger#31]
ADB error reads:
`Performing Streamed Install
adb: failed to install flinger.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1666857912.tmp/base.apk: Failed to load asset path /data/app/vmdl1666857912.tmp/base.apk]
`

OnePlus 8 Pro running Android 11

**Comment by iamjosephmj** [comment]
@ptrckSTL can you see if this works for you?
https://webapp.diawi.com/install/XwNprE

**Comment by ptrckSTL** [comment]
Works great, thank you!
